// <auto-generated />
using System;
using KCAS.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCAS.Admin.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607203500_AddReferenceDataClosure")]
    partial class AddReferenceDataClosure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KCAS.Admin.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("Email")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("WindowsAccountName")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("WindowsAccountName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KCAS.Admin.Data.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientFolder")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Initials")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KanaanId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("LegacyClientId")
                        .HasColumnType("int");

                    b.Property<string>("SurnameOrEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("KanaanId");

                    b.HasIndex("LegacyClientId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("LegacySourceField")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LinesRaw")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AddressType");

                    b.ToTable("ClientAddresses");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientContactPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LegacySourceField")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.HasIndex("ClientId", "ContactType", "IsPrimary");

                    b.ToTable("ClientContactPoints");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientFinancialProfile", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("BankDetailRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("CapitalRequirementPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Employer")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("EmployerPensionContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployerPensionContributionPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("ExpectedRetirementIncomePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("GrossAnnualSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossMonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumRetirementIncomePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("MonthlyExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OtherDetailsRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OtherGoalsRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("OtherIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PensionFundName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("PensionFundTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreservationFundLumpSumPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("RepresentativeAlternativeInvestmentsPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("RepresentativeEquitiesPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("RepresentativeFixedPropertyPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("RepresentativeOffshorePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("RetirementAge")
                        .HasColumnType("int");

                    b.Property<decimal?>("RetirementAnnuityTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetirementProvisionTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WillDetailRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("YearlyBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClientId");

                    b.ToTable("ClientFinancialProfiles");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientFundValuation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Administrator")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal?>("AmountForeign")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyClientNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("FundDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvestmentUniqueNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("KanaanId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("LegacyClientId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyFundId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOpenedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ValuationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvestmentUniqueNumber");

                    b.HasIndex("KanaanId");

                    b.HasIndex("LegacyClientId");

                    b.HasIndex("LegacyFundId")
                        .IsUnique();

                    b.HasIndex("ValuationDate");

                    b.ToTable("ClientFundValuations");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientInvestmentAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Administrator")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FundName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InvestmentDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLinkedHead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegacyAdministratorId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyClientId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyFundId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyInvestmentAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyLinkedAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOpenedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyProductId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyProductTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("SurrenderDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("ClientId");

                    b.HasIndex("LegacyClientId");

                    b.HasIndex("LegacyInvestmentAccountId")
                        .IsUnique();

                    b.HasIndex("LegacyLinkedAccountId");

                    b.ToTable("ClientInvestmentAccounts");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientInvestmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("AnnualIncreasePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("BalanceForeign")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BalanceZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientInvestmentAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("InvestmentAmountForeign")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InvestmentAmountZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvestmentFrequency")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegacyInvestmentAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyInvestmentHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOpenedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal?>("WithdrawalAmountForeign")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WithdrawalAmountZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientInvestmentAccountId");

                    b.HasIndex("LegacyInvestmentAccountId");

                    b.HasIndex("LegacyInvestmentHistoryId")
                        .IsUnique();

                    b.HasIndex("TransactionDate");

                    b.ToTable("ClientInvestmentTransactions");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientKycPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Administrator")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal?>("CapitalAdequacyRatioPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompulsoryContributionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DisabilityCover")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DreadDiseaseCover")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fund")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IncludeInCalculations")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPreservationFund")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsQuote")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRetirementAnnuity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRetrenchmentPackage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KanaanId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("LegacyClientId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyKycId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyMainClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOpenedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacySubClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LifeCover")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MainClassName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OnceOffPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Product")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SubClassExtra")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SubClassName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("SurrenderOrLiquidate")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("TaxPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ValuationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VoluntaryContributionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LegacyKycId");

                    b.HasIndex("PolicyNumber");

                    b.HasIndex("IncludeInCalculations", "IsQuote");

                    b.HasIndex("LegacyMainClassId", "LegacySubClassId");

                    b.ToTable("ClientKycPolicies");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientKycRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientKycPolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KanaanId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("LegacyClientId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyRecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Outcome")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RecommendationDate")
                        .HasColumnType("date");

                    b.Property<string>("RecommendationType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientKycPolicyId");

                    b.HasIndex("KanaanId");

                    b.HasIndex("LegacyRecommendationId");

                    b.HasIndex("Status");

                    b.ToTable("ClientKycRecommendations");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientLegacySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SourceTable", "SourceId");

                    b.ToTable("ClientLegacySnapshots");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegacyClientNoteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOpenedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NoteDate")
                        .HasColumnType("date");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyClientNoteId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("ClientId", "NoteDate");

                    b.ToTable("ClientNotes");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientPersonalProfile", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FamilyDetailRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HighestQualification")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("IsTaxClient")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NumberOfDependents")
                        .HasColumnType("int");

                    b.Property<bool?>("Smoker")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SouthAfricanIdNumber")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("WorkdayTravelPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("ClientId");

                    b.HasIndex("SouthAfricanIdNumber");

                    b.ToTable("ClientPersonalProfiles");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("Employer")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("EmployerPensionContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployerPensionContributionPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("GrossAnnualSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossMonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HighestQualification")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Initials")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("LegacyRelatedClientId")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("OtherIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PensionFundName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SouthAfricanIdNumber")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("YearlyBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "RelationshipType");

                    b.ToTable("ClientRelationships");
                });

            modelBuilder.Entity("KCAS.Admin.Data.InvestmentAdministratorReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegacyLispId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MonthlyUpload")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyLispId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("IsCurrent", "Name");

                    b.ToTable("InvestmentAdministratorReferences");
                });

            modelBuilder.Entity("KCAS.Admin.Data.InvestmentFundReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegacyAdministratorId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyFundNameId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyMainClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacySubClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MonthlyUpload")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyFundNameId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("ShortName");

                    b.HasIndex("IsCurrent", "Name");

                    b.HasIndex("LegacyAdministratorId", "LegacyMainClassId", "LegacySubClassId");

                    b.ToTable("InvestmentFundReferences");
                });

            modelBuilder.Entity("KCAS.Admin.Data.InvestmentProductTypeReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("LegacyCompanyProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyCompanyProductId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("InvestmentProductTypeReferences");
                });

            modelBuilder.Entity("KCAS.Admin.Data.KycMainClassReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AfrikaansDescription")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("EnglishDescription")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("LegacyMainClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyMainClassId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("KycMainClassReferences");
                });

            modelBuilder.Entity("KCAS.Admin.Data.KycSubClassReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KycMainClassReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyMainClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacySubClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyMainClassId");

                    b.HasIndex("LegacySubClassId")
                        .IsUnique();

                    b.HasIndex("KycMainClassReferenceId", "Name");

                    b.ToTable("KycSubClassReferences");
                });

            modelBuilder.Entity("KCAS.Admin.Data.MarketReferenceValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("LegacyMiscInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LegacyOpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LegacyUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OpenedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PriceDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyMiscInfoId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("PriceDate");

                    b.ToTable("MarketReferenceValues");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientAddress", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientContactPoint", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("ContactPoints")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientFinancialProfile", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithOne("FinancialProfile")
                        .HasForeignKey("KCAS.Admin.Data.ClientFinancialProfile", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientFundValuation", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("FundValuations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientInvestmentAccount", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("InvestmentAccounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientInvestmentTransaction", b =>
                {
                    b.HasOne("KCAS.Admin.Data.ClientInvestmentAccount", "InvestmentAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientInvestmentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentAccount");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientKycPolicy", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("KycPolicies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientKycRecommendation", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("KycRecommendations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KCAS.Admin.Data.ClientKycPolicy", "KycPolicy")
                        .WithMany()
                        .HasForeignKey("ClientKycPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("KycPolicy");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientLegacySnapshot", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("LegacySnapshots")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientNote", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("Notes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientPersonalProfile", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithOne("PersonalProfile")
                        .HasForeignKey("KCAS.Admin.Data.ClientPersonalProfile", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientRelationship", b =>
                {
                    b.HasOne("KCAS.Admin.Data.Client", "Client")
                        .WithMany("Relationships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KCAS.Admin.Data.KycSubClassReference", b =>
                {
                    b.HasOne("KCAS.Admin.Data.KycMainClassReference", "MainClass")
                        .WithMany("SubClasses")
                        .HasForeignKey("KycMainClassReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainClass");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KCAS.Admin.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KCAS.Admin.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KCAS.Admin.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KCAS.Admin.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KCAS.Admin.Data.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactPoints");

                    b.Navigation("FinancialProfile");

                    b.Navigation("FundValuations");

                    b.Navigation("InvestmentAccounts");

                    b.Navigation("KycPolicies");

                    b.Navigation("KycRecommendations");

                    b.Navigation("LegacySnapshots");

                    b.Navigation("Notes");

                    b.Navigation("PersonalProfile");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("KCAS.Admin.Data.ClientInvestmentAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("KCAS.Admin.Data.KycMainClassReference", b =>
                {
                    b.Navigation("SubClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
